In [1]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np

In [3]:
iris=load_iris()
dt_clf = DecisionTreeClassifier()

In [4]:
train_data = iris.data

In [5]:
train_label = iris.target

In [6]:
len(train_label)

150

In [7]:
train_data.shape

(150, 4)

In [8]:
iris.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

In [9]:
train_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
dt_clf.fit(train_data, train_label)

DecisionTreeClassifier()

In [11]:
dt_clf.predict(train_data)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
print(accuracy_score(train_label, dt_clf.predict(train_data)))#정답, 예측값

1.0


In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(train_data, train_label,test_size=0.3, random_state=14)

In [14]:
X_train.shape

(105, 4)

In [15]:
y_train.shape

(105,)

In [16]:
y_train

array([2, 0, 0, 0, 1, 0, 0, 2, 2, 1, 2, 2, 0, 1, 2, 1, 1, 2, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 0, 0, 2, 0, 2, 0, 0, 2, 1, 0, 1, 2, 2, 2,
       1, 1, 2, 1, 2, 2, 2, 0, 2, 1, 1, 0, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 2, 2, 0, 2, 0, 1, 2, 0, 1, 0, 0, 2, 2, 2, 0, 2, 2, 1, 1, 0, 2,
       2, 0, 2, 1, 0, 2, 0, 0, 0, 2, 1, 2, 2, 1, 0, 1, 2])

In [17]:
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [18]:
print(accuracy_score(y_test, dt_clf.predict(X_test)))#정답, 예측값(seed=11)

0.9555555555555556


In [19]:
print(accuracy_score(y_test, dt_clf.predict(X_test)))#정답, 예측값(seed=12)

0.9555555555555556


In [20]:
print(accuracy_score(y_test, dt_clf.predict(X_test)))#정답, 예측값(seed=13)

0.9555555555555556


In [21]:
print(accuracy_score(y_test, dt_clf.predict(X_test)))#정답, 예측값(seed=14)

0.9555555555555556


---------------
## KFold

In [22]:
from sklearn.model_selection import KFold
kfold = KFold(n_splits=5)
cv_acc = []
print("붓꽃 데이터 세트 크기: ", train_data.shape[0])

붓꽃 데이터 세트 크기:  150


In [23]:
n_iter = 0
#KFold객체의 split()를 호출하면 폴드 별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환
for train_index,test_index in kfold.split(train_data):
    #kfold.split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = train_data[train_index], train_data[test_index]
    y_train, y_test = train_label[train_index], train_label[test_index]
    #학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter+=1
    #반복 시마다 정확도 측정
    acc = np.round(accuracy_score(y_test,pred),4)
    train_size= X_train.shape[0]
    test_size= X_test.shape[0]
    print(f"\n {n_iter}. 교차 검증 정확도:{acc}, 학습 데이터 크기:{train_size}, 검증 데이터 크기: {test_size}")
    print(f"검증 세트 인덱스: {test_index}")
    cv_acc.append(acc)
    
print(f"\n평균 검증 정확도: {np.mean(cv_acc)}")


 1. 교차 검증 정확도:1.0, 학습 데이터 크기:120, 검증 데이터 크기: 30
검증 세트 인덱스: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

 2. 교차 검증 정확도:1.0, 학습 데이터 크기:120, 검증 데이터 크기: 30
검증 세트 인덱스: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

 3. 교차 검증 정확도:0.9, 학습 데이터 크기:120, 검증 데이터 크기: 30
검증 세트 인덱스: [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

 4. 교차 검증 정확도:0.9333, 학습 데이터 크기:120, 검증 데이터 크기: 30
검증 세트 인덱스: [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

 5. 교차 검증 정확도:0.7667, 학습 데이터 크기:120, 검증 데이터 크기: 30
검증 세트 인덱스: [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

평균 검증 정확도: 0.9199999999999999


-------------
## Stratified KFold
- 불균형한 분포도(특정 레이블 값이 월등히 많은 경우)를 가진 레이블 데이터 집합을 위한 방식

In [24]:
iris_df = pd.DataFrame(iris.data, columns =iris.feature_names)
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [25]:
iris_df['label'] = train_label
iris_df['label'].value_counts()

2    50
1    50
0    50
Name: label, dtype: int64

In [26]:
#일단 그냥 KFold
kfold = KFold(n_splits=3)
n_iter=0
for train_index,test_index in kfold.split(train_data):
    n_iter+=1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print(f"{n_iter}. 교차검증\n")
    print(f"학습 레이블 데이터 분포:\n{label_train.value_counts()}\n")
    print(f"검증 레이블 데이터 분포:\n{label_test.value_counts()}") 
    print("\n")

1. 교차검증

학습 레이블 데이터 분포:
2    50
1    50
Name: label, dtype: int64

검증 레이블 데이터 분포:
0    50
Name: label, dtype: int64


2. 교차검증

학습 레이블 데이터 분포:
2    50
0    50
Name: label, dtype: int64

검증 레이블 데이터 분포:
1    50
Name: label, dtype: int64


3. 교차검증

학습 레이블 데이터 분포:
1    50
0    50
Name: label, dtype: int64

검증 레이블 데이터 분포:
2    50
Name: label, dtype: int64




-----------
위와 같은 경우,<br>
검증 score가 높게 나올 수가 없음

In [27]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=3)
n_iter =0

In [28]:
for train_index,test_index in skf.split(iris_df, iris_df['label']):
    n_iter+=1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print(f"{n_iter}. 교차검증\n")
    print(f"학습 레이블 데이터 분포:\n{label_train.value_counts()}\n")
    print(f"검증 레이블 데이터 분포:\n{label_test.value_counts()}") 
    print("\n")

1. 교차검증

학습 레이블 데이터 분포:
2    34
1    33
0    33
Name: label, dtype: int64

검증 레이블 데이터 분포:
1    17
0    17
2    16
Name: label, dtype: int64


2. 교차검증

학습 레이블 데이터 분포:
1    34
2    33
0    33
Name: label, dtype: int64

검증 레이블 데이터 분포:
2    17
0    17
1    16
Name: label, dtype: int64


3. 교차검증

학습 레이블 데이터 분포:
0    34
2    33
1    33
Name: label, dtype: int64

검증 레이블 데이터 분포:
2    17
1    17
0    16
Name: label, dtype: int64




----
KFold로 분할된 레이블이 전체 레이블 값의 분포도를 반영하지 못하는 문제를 해결해줌<br>
그래서 split메서드에 인자로 피처뿐만 아니라 레이블 데이터도 반드시 필요하다. 

------------
## Cross Validation score
- KFold로 데이터를 학습하고 예측하는 코드를 간결하게 해주는 API

In [29]:
from sklearn.model_selection import cross_val_score, cross_validate

In [30]:
#성능 지표는 acc , 교차 검증 세트는 3개
scores = cross_val_score(dt_clf,iris.data, iris.target, scoring='accuracy', cv=3)

In [31]:
print("교차 검증별 정확도:",np.round(scores,4))
print("평균: ",np.round(np.mean(scores),4))

교차 검증별 정확도: [0.98 0.92 1.  ]
평균:  0.9667


In [32]:
print(cross_val_score(dt_clf, X_train, y_train,scoring="accuracy",cv=3).mean())

0.9583333333333334


In [33]:
#여러개의 평가지표 가능
cross_validate(dt_clf, X_train, y_train, scoring=['accuracy','f1_micro'],cv=3, return_train_score=True)#다중분류라 roc, f1, precision등은 X

{'fit_time': array([0., 0., 0.]),
 'score_time': array([0.00199389, 0.0009973 , 0.00099277]),
 'test_accuracy': array([1.   , 0.95 , 0.925]),
 'train_accuracy': array([1., 1., 1.]),
 'test_f1_micro': array([1.   , 0.95 , 0.925]),
 'train_f1_micro': array([1., 1., 1.])}

-------
## GridSearchCV : 교차검증+최적화

In [35]:
from sklearn.model_selection import GridSearchCV
grid_param = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [36]:
grid_dt = GridSearchCV(dt_clf, param_grid = grid_param, cv=3, refit=True)

In [39]:
grid_dt.fit(X_train, y_train)
scores_df= pd.DataFrame(grid_dt.cv_results_)

In [44]:
scores_df[['params','mean_test_score','rank_test_score','split0_test_score','split1_test_score','split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.833333                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.833333                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                1   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                1   
4  {'max_depth': 3, 'min_samples_split': 2}         0.950000                3   
5  {'max_depth': 3, 'min_samples_split': 3}         0.950000                3   

   split0_test_score  split1_test_score  split2_test_score  
0              0.850              0.825              0.825  
1              0.850              0.825              0.825  
2              1.000              0.950              0.925  
3              1.000              0.950              0.925  
4              0.975              0.950              0.925  
5              0.975              0.950              0.925

 -----------------------
 # Data Encoding 
 


## Label Encoding

In [45]:
from sklearn.preprocessing import LabelEncoder
label_en = LabelEncoder()

In [51]:
iris_y=label_en.transform(iris.feature_names)

In [54]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [52]:
iris_y

array([2, 3, 0, 1], dtype=int64)

## One-Hot Encoding

In [59]:
#방법1
from sklearn.preprocessing import OneHotEncoder
one_en = OneHotEncoder()
#2차원 데이터로 변환해야함
one_en.fit(iris_y.reshape(-1,1))
iris_y2 = one_en.transform(iris_y.reshape(-1,1))

In [61]:
iris_y2.shape

(4, 4)

In [62]:
#방법2
pd.get_dummies(iris.feature_names)

petal length (cm)  petal width (cm)  sepal length (cm)  sepal width (cm)
0                  0                 0                  1                 0
1                  0                 0                  0                 1
2                  1                 0                  0                 0
3                  0                 1                  0                 0

--------------
# 피처 스케일링과 정규화

## StandardScaler

In [64]:
iris_df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)       label  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [72]:
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
scaler = StandardScaler()
scaler.fit(iris_df)

StandardScaler()

In [73]:
iris_scaled = pd.DataFrame(scaler.transform(iris_df))
iris_scaled.describe()

0             1             2             3             4
count  1.500000e+02  1.500000e+02  1.500000e+02  1.500000e+02  1.500000e+02
mean  -4.736952e-16 -7.815970e-16 -4.263256e-16 -4.736952e-16 -1.421085e-16
std    1.003350e+00  1.003350e+00  1.003350e+00  1.003350e+00  1.003350e+00
min   -1.870024e+00 -2.433947e+00 -1.567576e+00 -1.447076e+00 -1.224745e+00
25%   -9.006812e-01 -5.923730e-01 -1.226552e+00 -1.183812e+00 -1.224745e+00
50%   -5.250608e-02 -1.319795e-01  3.364776e-01  1.325097e-01  0.000000e+00
75%    6.745011e-01  5.586108e-01  7.627583e-01  7.906707e-01  1.224745e+00
max    2.492019e+00  3.090775e+00  1.785832e+00  1.712096e+00  1.224745e+00

In [74]:
print(iris_scaled.mean())

0   -2.775558e-16
1   -9.695948e-16
2   -8.652338e-16
3   -4.662937e-16
4    1.184238e-17
dtype: float64


In [75]:
print(iris_scaled.var())

0    1.006711
1    1.006711
2    1.006711
3    1.006711
4    1.006711
dtype: float64


## MinMaxScaler

In [76]:
from sklearn.preprocessing import MinMaxScaler
scaler= MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

In [79]:
iris_scaled = pd.DataFrame(iris_scaled)
iris_scaled.describe()

0           1           2           3           4
count  150.000000  150.000000  150.000000  150.000000  150.000000
mean     0.428704    0.440556    0.467458    0.458056    0.500000
std      0.230018    0.181611    0.299203    0.317599    0.409616
min      0.000000    0.000000    0.000000    0.000000    0.000000
25%      0.222222    0.333333    0.101695    0.083333    0.000000
50%      0.416667    0.416667    0.567797    0.500000    0.500000
75%      0.583333    0.541667    0.694915    0.708333    1.000000
max      1.000000    1.000000    1.000000    1.000000    1.000000